version: 2

project_name: url-harvester

builds:
  - id: url-harvester
    main: ./cmd/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    binary: url-harvester

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  github:
    owner: "mihneamanolache"
    name: "url-harvester"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
